name: Mac platform_channel_sample_test_swift

on:
  # Post-submit.
  push:
    branches: [main]

  # Pre-submit.
  pull_request:
    branches: [main]

  # Cron job: Every 15m.
  # schedule:
  #   - cron: "*/15 * * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Flutter
        run: ./setup.sh

      - name: Setup PATH
        run: |
          echo "export PATH=\$PATH:${{github.workspace}}/vendor/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Doctor
        run: flutter doctor

      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 8"

      - name: Flutter Devices
        run: flutter devices

      - name: Run Test
        run: |
          pushd vendor/flutter/dev/devicelab
          dart pub get
          dart run bin/run.dart --task platform_channel_sample_test_swift
          popd
